{ Program to automatically generate a VGAPAL.PAS file
   containing a constant with the standard VGA Palette in it 

  I'm doing this as I've found some cards do not have the same default
  palette, so this is for correcting visual issues.

  A Danson 2013
}

{$G+}

program palgen;

uses buffer, palette,vgavesa;

var
   out	 : writer;
   pal	 : paltype;
   i	 : integer;
   s	 : string;
   a,b,c : string;

begin
   vga256(0);
   getPalette(pal);
   closevid;

   out.open('vgapal.pas');

   out.writeln('{ Palette constant generated by palgen }');
   out.writeln('');
   out.writeln('unit vgapal;');
   out.writeln('');
   out.writeln('interface');
   out.writeln('  uses palette;');
   out.writeln('');
   out.writeln('const');
   out.writeln('  stdpal : paltype = (');
   for i:= 0 to 255 do
   begin
      str(pal[i,0],a);
      str(pal[i,1],b);
      str(pal[i,2],c);
      s:='    ('+a+' , '+b+' , '+c+')';
      if (i<255) then s:=s+',';
      out.writeln(s);
   end;
   out.writeln('   );');

   out.writeln('');
   out.writeln('implementation');
   out.writeln('');
   out.writeln('end.');
   out.close;

end.
